// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4930.Timrek.subsystems;

import org.usfirst.frc4930.Timrek.RobotMap;
import org.usfirst.frc4930.Timrek.Values;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Gripper extends Subsystem {

    @Override
    public void initDefaultCommand() {

    }

    @Override
    public void periodic() {

    }
    
    public void set(double speed) {
    	// the right motor is set to follow the left
    	RobotMap.lIntake.set(speed);
    }
    
    public void testMotor(int id, double speed) {
    	switch(id) {
    		case Values.L_INTAKE_ID:
    			RobotMap.lIntake.set(speed);
    			break;
    		case Values.R_INTAKE_ID:
    			RobotMap.rIntake.set(speed);
    			break;
    			
    		default:
    			System.out.println("Invalid Gripper Motor ID");
    			break;
    	}
    }

}

