
// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4930.Timrek.subsystems;

import org.usfirst.frc4930.Timrek.RobotMap;
import org.usfirst.frc4930.Timrek.Constants;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */


public class Gripper extends Subsystem {

	@Override
	protected void initDefaultCommand() {
		// TODO Auto-generated method stub
		
	}

	public void grip(double speed) {
		RobotMap.lIntake.set(speed);
		RobotMap.rIntake.set(speed);
	}
	
	public void stop() {
		RobotMap.lIntake.stopMotor();
		RobotMap.rIntake.stopMotor();
	}
}

