// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4930.Timrek;

import org.usfirst.frc4930.Timrek.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
	public Joystick j0;
	public Joystick j1;
	public Joystick j2;
	
	
	public JoystickButton j2b3;
	public JoystickButton j2b4;
	public JoystickButton j2b8;
	public JoystickButton j2b9;
	public JoystickButton j2b10;
	public JoystickButton j2b11;
	public JoystickButton j2b12;
	
    public OI() {
       j0 = new Joystick(0);
       j1 = new Joystick(1);
       j2 = new Joystick(2);

       j2b8 = new JoystickButton(j2, 8);
       j2b9 = new JoystickButton(j2, 9);
       j2b10 = new JoystickButton(j2, 10);
       j2b11 = new JoystickButton(j2, 11);
       j2b12 = new JoystickButton(j2, 12);
       j2b3 = new JoystickButton(j2, 3);
       j2b4 = new JoystickButton(j2, 4);
       
       j2b3.whileHeld(new Intake());
       j2b4.whileHeld(new Outtake());
       
       j2b8.whenPressed(new Ground());
       j2b9.whenPressed(new UpperArmMove(1));
       j2b10.whenPressed(new UpperArmMove(2));
       
    //   j2b11.whenPressed(new LowerArmMove());
       j2b12.whenPressed(new UpperArmMove(3));
       
       
        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

